package model.dbentities;
// Generated Nov 25, 2017 12:14:20 PM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private int adminId;
     private String adminName;
     private String email;
     private String password;
     private int ranked;

    public Admin() {
    }

	
    public Admin(int adminId, int ranked) {
        this.adminId = adminId;
        this.ranked = ranked;
    }
    public Admin(int adminId, String adminName, String email, String password, int ranked) {
       this.adminId = adminId;
       this.adminName = adminName;
       this.email = email;
       this.password = password;
       this.ranked = ranked;
    }
   
    public int getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getRanked() {
        return this.ranked;
    }
    
    public void setRanked(int ranked) {
        this.ranked = ranked;
    }




}


