package model.dbentities;
// Generated Nov 25, 2017 12:14:20 PM by Hibernate Tools 4.3.1



/**
 * OrderDetailId generated by hbm2java
 */
public class OrderDetailId  implements java.io.Serializable {


     private int orderId;
     private String keyId;

    public OrderDetailId() {
    }

    public OrderDetailId(int orderId, String keyId) {
       this.orderId = orderId;
       this.keyId = keyId;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public String getKeyId() {
        return this.keyId;
    }
    
    public void setKeyId(String keyId) {
        this.keyId = keyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderDetailId) ) return false;
		 OrderDetailId castOther = ( OrderDetailId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && ( (this.getKeyId()==castOther.getKeyId()) || ( this.getKeyId()!=null && castOther.getKeyId()!=null && this.getKeyId().equals(castOther.getKeyId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + ( getKeyId() == null ? 0 : this.getKeyId().hashCode() );
         return result;
   }   


}


