package model.dbentities;
// Generated Nov 25, 2017 12:14:20 PM by Hibernate Tools 4.3.1



/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private OrderDetailId id;
     private Order order;
     private ProductKey productKey;
     private Integer status;

    public OrderDetail() {
    }

	
    public OrderDetail(OrderDetailId id, Order order, ProductKey productKey) {
        this.id = id;
        this.order = order;
        this.productKey = productKey;
    }
    public OrderDetail(OrderDetailId id, Order order, ProductKey productKey, Integer status) {
       this.id = id;
       this.order = order;
       this.productKey = productKey;
       this.status = status;
    }
   
    public OrderDetailId getId() {
        return this.id;
    }
    
    public void setId(OrderDetailId id) {
        this.id = id;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public ProductKey getProductKey() {
        return this.productKey;
    }
    
    public void setProductKey(ProductKey productKey) {
        this.productKey = productKey;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


