package model.dbentities;
// Generated Oct 21, 2017 10:21:01 PM by Hibernate Tools 4.3.1



/**
 * ProductImage generated by hbm2java
 */
public class ProductImage  implements java.io.Serializable {


     private int imageId;
     private ProductDetail productDetail;
     private String imageLink;
     private Byte isAva;
     private Byte flag;
     private Byte imageType;

    public ProductImage() {
    }

	
    public ProductImage(int imageId) {
        this.imageId = imageId;
    }
    public ProductImage(int imageId, ProductDetail productDetail, String imageLink, Byte isAva, Byte flag) {
       this.imageId = imageId;
       this.productDetail = productDetail;
       this.imageLink = imageLink;
       this.isAva = isAva;
       this.flag = flag;
    }

    public ProductImage(int imageId, ProductDetail productDetail, String imageLink, Byte isAva, Byte flag, Byte imageType) {
        this.imageId = imageId;
        this.productDetail = productDetail;
        this.imageLink = imageLink;
        this.isAva = isAva;
        this.flag = flag;
        this.imageType = imageType;
    }
   
    public int getImageId() {
        return this.imageId;
    }
    
    public void setImageId(int imageId) {
        this.imageId = imageId;
    }
    public ProductDetail getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(ProductDetail productDetail) {
        this.productDetail = productDetail;
    }
    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }
    public Byte getIsAva() {
        return this.isAva;
    }
    
    public void setIsAva(Byte isAva) {
        this.isAva = isAva;
    }
    public Byte getFlag() {
        return this.flag;
    }
    
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    public Byte getImageType() {
        return imageType;
    }

    public void setImageType(Byte imageType) {
        this.imageType = imageType;
    }




}


