package model.dbentities;
// Generated Nov 25, 2017 12:14:20 PM by Hibernate Tools 4.3.1



/**
 * ProductImage generated by hbm2java
 */
public class ProductImage  implements java.io.Serializable {
     private int imageId;
     private ProductDetail productDetail;
     private String imageLink;
     private Integer isAva;
     private Integer flag;
     private Integer imageType;

    public ProductImage() {
    }

	
    public ProductImage(int imageId) {
        this.imageId = imageId;
    }
    public ProductImage(int imageId, ProductDetail productDetail, String imageLink, Integer isAva, Integer flag, Integer imageType) {
       this.imageId = imageId;
       this.productDetail = productDetail;
       this.imageLink = imageLink;
       this.isAva = isAva;
       this.flag = flag;
       this.imageType = imageType;
    }
   
    public int getImageId() {
        return this.imageId;
    }
    
    public void setImageId(int imageId) {
        this.imageId = imageId;
    }
    public ProductDetail getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(ProductDetail productDetail) {
        this.productDetail = productDetail;
    }
    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }
    public Integer getIsAva() {
        return this.isAva;
    }
    
    public void setIsAva(Integer isAva) {
        this.isAva = isAva;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Integer getImageType() {
        return this.imageType;
    }
    
    public void setImageType(Integer imageType) {
        this.imageType = imageType;
    }




}


