package model.dbentities;
// Generated Nov 25, 2017 12:14:20 PM by Hibernate Tools 4.3.1


import java.util.*;

/**
 * ProductDetail generated by hbm2java
 */
public class ProductDetail  implements java.io.Serializable {


     private Integer productId;
     private Manufacturer manufacturer;
     private Type type;
     private String productName;
     private Date releaseTime;
     private Integer status;
     private String language;
     private String region;
     private String description;
     private String introduction;
     private double price;
     private Integer viewedNumber;
     private Set productImages = new HashSet(0);
     private Set productKeys = new HashSet(0);

    private String thumbnailUrl; 
    private String bannerStatus = ""; 

    public ProductDetail() {
    }

	
    public ProductDetail(String productName, double price) {
        this.productName = productName;
        this.price = price;
    }
    public ProductDetail(Manufacturer manufacturer, Type type, String productName, Date releaseTime, Integer status, String language, String region, String description, String introduction, double price, Integer viewedNumber, Set productImages, Set productKeys) {
       this.manufacturer = manufacturer;
       this.type = type;
       this.productName = productName;
       this.releaseTime = releaseTime;
       this.status = status;
       this.language = language;
       this.region = region;
       this.description = description;
       this.introduction = introduction;
       this.price = price;
       this.viewedNumber = viewedNumber;
       this.productImages = productImages;
       this.productKeys = productKeys;
    }
   
    public static void getThumnailImage(List<ProductDetail> lstProduct){
        for (ProductDetail product : lstProduct){
            Iterator itr = product.productImages.iterator();
            product.thumbnailUrl = "images/product/product1.jpg";
            while (itr.hasNext()){
                ProductImage img = (ProductImage) itr.next();
                if (img.getFlag() == 1 && img.getIsAva() == 1){
                    product.thumbnailUrl = img.getImageLink();
                    break;
                }
            }
        }
    }
    
    public static void getThumnailImage(ProductDetail product){
        Iterator itr = product.productImages.iterator();
        product.thumbnailUrl = "images/product/product1.jpg";
        while (itr.hasNext()){
            ProductImage img = (ProductImage) itr.next();
            if (img.getFlag() == 1 && img.getIsAva() == 1){
                product.thumbnailUrl = img.getImageLink();
                break;
            }
        }
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public Manufacturer getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(Manufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Date getReleaseTime() {
        return this.releaseTime;
    }
    
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getIntroduction() {
        return this.introduction;
    }
    
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Integer getViewedNumber() {
        return this.viewedNumber;
    }
    
    public void setViewedNumber(Integer viewedNumber) {
        this.viewedNumber = viewedNumber;
    }
    public Set getProductImages() {
        return this.productImages;
    }
    
    public void setProductImages(Set productImages) {
        this.productImages = productImages;
    }
    public Set getProductKeys() {
        return this.productKeys;
    }
    
    public void setProductKeys(Set productKeys) {
        this.productKeys = productKeys;
    }

    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    public void setThumbnailUrl(String thumbnailUrl) {
        this.thumbnailUrl = thumbnailUrl;
    }

    public String getBannerStatus() {
        return bannerStatus;
    }

    public void setBannerStatus(String bannerStatus) {
        this.bannerStatus = bannerStatus;
    }




}


