package model.dbentities;
// Generated Nov 25, 2017 12:14:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import util.Util;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private Integer userId;
    private String userName;
    private String password;
    private String email;
    private String phoneNumber;
    private Integer gender;
    private String address;
    private Date dateOfBirth;
    private Double money;
    private Set orders = new HashSet(0);

    public User() {
    }

    public User(String userName, String password, String email, String phoneNumber, Integer gender, String address, Date dateOfBirth, Double money, Set orders) {
        this.userName = userName;
        this.password = password;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.gender = gender;
        this.address = address;
        this.dateOfBirth = dateOfBirth;
        this.money = money;
        this.orders = orders;
    }

    public User(String userName, String password, String email, String phoneNumber, String gender, String address, String dateOfBirth) {
        this.userName = userName;
        this.password = password;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.gender = Integer.parseInt(gender);
        this.address = address;
        this.money = 0.0;
        String[] date = dateOfBirth.split("-");
        this.dateOfBirth = new Date(Integer.parseInt(date[0]) - 1901, Integer.parseInt(date[1]), Integer.parseInt(date[1]));
    }

    public User(String userId, String userName, String email, String phoneNumber, String address, String dateOfBirth) {
        this.userId = Integer.parseInt(userId);
        this.userName = userName;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.dateOfBirth = Util.format(dateOfBirth);
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Integer getGender() {
        return this.gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public Double getMoney() {
        return this.money;
    }

    public void setMoney(Double money) {
        this.money = money;
    }

    public Set getOrders() {
        return this.orders;
    }

    public void setOrders(Set orders) {
        this.orders = orders;
    }

}
