package entities;
// Generated Jun 7, 2016 9:33:33 PM by Hibernate Tools 4.3.1


/**
 * Allorder generated by hbm2java
 */
public class Allorder {


     private int orderId;
     private Method method;
     private Product product;
     private Userkey userkey;
     private String orderPayment;
     private String orderPstatus;
     private int number;
     private int finistnum;

    public Allorder() {
    }

	
    public Allorder(int orderId, Method method, Product product, Userkey userkey, int number, int finistnum) {
        this.orderId = orderId;
        this.method = method;
        this.product = product;
        this.userkey = userkey;
        this.number = number;
        this.finistnum = finistnum;
    }
    public Allorder(int orderId, Method method, Product product, Userkey userkey, String orderPayment, String orderPstatus, int number, int finistnum) {
       this.orderId = orderId;
       this.method = method;
       this.product = product;
       this.userkey = userkey;
       this.orderPayment = orderPayment;
       this.orderPstatus = orderPstatus;
       this.number = number;
       this.finistnum = finistnum;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public Method getMethod() {
        return this.method;
    }
    
    public void setMethod(Method method) {
        this.method = method;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Userkey getUserkey() {
        return this.userkey;
    }
    
    public void setUserkey(Userkey userkey) {
        this.userkey = userkey;
    }
    public String getOrderPayment() {
        return this.orderPayment;
    }
    
    public void setOrderPayment(String orderPayment) {
        this.orderPayment = orderPayment;
    }
    public String getOrderPstatus() {
        return this.orderPstatus;
    }
    
    public void setOrderPstatus(String orderPstatus) {
        this.orderPstatus = orderPstatus;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    public int getFinistnum() {
        return this.finistnum;
    }
    
    public void setFinistnum(int finistnum) {
        this.finistnum = finistnum;
    }




}


