package entities;
// Generated Jun 7, 2016 9:33:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Catalog generated by hbm2java
 */
public class Catalog{


     private int catalogId;
     private String catalogName;
     private Set gametypes = new HashSet(0);

    public Catalog() {
    }

	
    public Catalog(int catalogId, String catalogName) {
        this.catalogId = catalogId;
        this.catalogName = catalogName;
    }
    public Catalog(int catalogId, String catalogName, Set gametypes) {
       this.catalogId = catalogId;
       this.catalogName = catalogName;
       this.gametypes = gametypes;
    }
   
    public int getCatalogId() {
        return this.catalogId;
    }
    
    public void setCatalogId(int catalogId) {
        this.catalogId = catalogId;
    }
    public String getCatalogName() {
        return this.catalogName;
    }
    
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }
    public Set getGametypes() {
        return this.gametypes;
    }
    
    public void setGametypes(Set gametypes) {
        this.gametypes = gametypes;
    }




}


