package entities;
// Generated Jun 7, 2016 9:33:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gametype generated by hbm2java
 */
public class Gametype {


     private int gametypeId;
     private Catalog catalog;
     private String gametypeName;
     private Set products = new HashSet(0);

    public Gametype() {
    }

	
    public Gametype(int gametypeId, Catalog catalog, String gametypeName) {
        this.gametypeId = gametypeId;
        this.catalog = catalog;
        this.gametypeName = gametypeName;
    }
    public Gametype(int gametypeId, Catalog catalog, String gametypeName, Set products) {
       this.gametypeId = gametypeId;
       this.catalog = catalog;
       this.gametypeName = gametypeName;
       this.products = products;
    }
   
    public int getGametypeId() {
        return this.gametypeId;
    }
    
    public void setGametypeId(int gametypeId) {
        this.gametypeId = gametypeId;
    }
    public Catalog getCatalog() {
        return this.catalog;
    }
    
    public void setCatalog(Catalog catalog) {
        this.catalog = catalog;
    }
    public String getGametypeName() {
        return this.gametypeName;
    }
    
    public void setGametypeName(String gametypeName) {
        this.gametypeName = gametypeName;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


