package entities;
// Generated Jun 7, 2016 9:33:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product {


     private int productId;
     private Gametype gametype;
     private Saled saled;
     private String productName;
     private int prince;
     private Date timeRelease;
     private String images;
     private String productStatus;
     private String language;
     private String regime;
     private String region;
     private String ative;
     private String manufacturer;
     private String typetext;
     private String headcontext;
     private String context;
     private String linkvideo;
     private String linkbanner;
     private String statusbanner;
     private int numberview;
     private Set allorders = new HashSet(0);
     private Set productKeys = new HashSet(0);

    public Product() {
    }

	
    public Product(int productId, Gametype gametype, Saled saled, String productName, int prince, String images, int numberview) {
        this.productId = productId;
        this.gametype = gametype;
        this.saled = saled;
        this.productName = productName;
        this.prince = prince;
        this.images = images;
        this.numberview = numberview;
    }
    public Product(int productId, Gametype gametype, Saled saled, String productName, int prince, Date timeRelease, String images, String productStatus, String language, String regime, String region, String ative, String manufacturer, String typetext, String headcontext, String context, String linkvideo, String linkbanner, String statusbanner, int numberview, Set allorders, Set productKeys) {
       this.productId = productId;
       this.gametype = gametype;
       this.saled = saled;
       this.productName = productName;
       this.prince = prince;
       this.timeRelease = timeRelease;
       this.images = images;
       this.productStatus = productStatus;
       this.language = language;
       this.regime = regime;
       this.region = region;
       this.ative = ative;
       this.manufacturer = manufacturer;
       this.typetext = typetext;
       this.headcontext = headcontext;
       this.context = context;
       this.linkvideo = linkvideo;
       this.linkbanner = linkbanner;
       this.statusbanner = statusbanner;
       this.numberview = numberview;
       this.allorders = allorders;
       this.productKeys = productKeys;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public Gametype getGametype() {
        return this.gametype;
    }
    
    public void setGametype(Gametype gametype) {
        this.gametype = gametype;
    }
    public Saled getSaled() {
        return this.saled;
    }
    
    public void setSaled(Saled saled) {
        this.saled = saled;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public int getPrince() {
        return this.prince;
    }
    
    public void setPrince(int prince) {
        this.prince = prince;
    }
    public Date getTimeRelease() {
        return this.timeRelease;
    }
    
    public void setTimeRelease(Date timeRelease) {
        this.timeRelease = timeRelease;
    }
    public String getImages() {
        return this.images;
    }
    
    public void setImages(String images) {
        this.images = images;
    }
    public String getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public String getRegime() {
        return this.regime;
    }
    
    public void setRegime(String regime) {
        this.regime = regime;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getAtive() {
        return this.ative;
    }
    
    public void setAtive(String ative) {
        this.ative = ative;
    }
    public String getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }
    public String getTypetext() {
        return this.typetext;
    }
    
    public void setTypetext(String typetext) {
        this.typetext = typetext;
    }
    public String getHeadcontext() {
        return this.headcontext;
    }
    
    public void setHeadcontext(String headcontext) {
        this.headcontext = headcontext;
    }
    public String getContext() {
        return this.context;
    }
    
    public void setContext(String context) {
        this.context = context;
    }
    public String getLinkvideo() {
        return this.linkvideo;
    }
    
    public void setLinkvideo(String linkvideo) {
        this.linkvideo = linkvideo;
    }
    public String getLinkbanner() {
        return this.linkbanner;
    }
    
    public void setLinkbanner(String linkbanner) {
        this.linkbanner = linkbanner;
    }
    public String getStatusbanner() {
        return this.statusbanner;
    }
    
    public void setStatusbanner(String statusbanner) {
        this.statusbanner = statusbanner;
    }
    public int getNumberview() {
        return this.numberview;
    }
    
    public void setNumberview(int numberview) {
        this.numberview = numberview;
    }
    public Set getAllorders() {
        return this.allorders;
    }
    
    public void setAllorders(Set allorders) {
        this.allorders = allorders;
    }
    public Set getProductKeys() {
        return this.productKeys;
    }
    
    public void setProductKeys(Set productKeys) {
        this.productKeys = productKeys;
    }




}


