package entities;
// Generated Jun 7, 2016 9:33:33 PM by Hibernate Tools 4.3.1



/**
 * ProductKey generated by hbm2java
 */
public class ProductKey{


     private int idProductkey;
     private Product product;
     private String productkeyKey;

    public ProductKey() {
    }

    public ProductKey(int idProductkey, Product product, String productkeyKey) {
       this.idProductkey = idProductkey;
       this.product = product;
       this.productkeyKey = productkeyKey;
    }
   
    public int getIdProductkey() {
        return this.idProductkey;
    }
    
    public void setIdProductkey(int idProductkey) {
        this.idProductkey = idProductkey;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getProductkeyKey() {
        return this.productkeyKey;
    }
    
    public void setProductkeyKey(String productkeyKey) {
        this.productkeyKey = productkeyKey;
    }




}


