package entities;
// Generated Jun 7, 2016 9:33:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ranked generated by hbm2java
 */
public class Ranked {


     private int rankId;
     private String rankName;
     private Set userkeys = new HashSet(0);

    public Ranked() {
    }

	
    public Ranked(int rankId, String rankName) {
        this.rankId = rankId;
        this.rankName = rankName;
    }
    public Ranked(int rankId, String rankName, Set userkeys) {
       this.rankId = rankId;
       this.rankName = rankName;
       this.userkeys = userkeys;
    }
   
    public int getRankId() {
        return this.rankId;
    }
    
    public void setRankId(int rankId) {
        this.rankId = rankId;
    }
    public String getRankName() {
        return this.rankName;
    }
    
    public void setRankName(String rankName) {
        this.rankName = rankName;
    }
    public Set getUserkeys() {
        return this.userkeys;
    }
    
    public void setUserkeys(Set userkeys) {
        this.userkeys = userkeys;
    }




}


