package entities;
// Generated Jun 7, 2016 9:33:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Saled generated by hbm2java
 */
public class Saled{


     private int salesId;
     private int sale;
     private Set products = new HashSet(0);

    public Saled() {
    }

	
    public Saled(int salesId, int sale) {
        this.salesId = salesId;
        this.sale = sale;
    }
    public Saled(int salesId, int sale, Set products) {
       this.salesId = salesId;
       this.sale = sale;
       this.products = products;
    }
   
    public int getSalesId() {
        return this.salesId;
    }
    
    public void setSalesId(int salesId) {
        this.salesId = salesId;
    }
    public int getSale() {
        return this.sale;
    }
    
    public void setSale(int sale) {
        this.sale = sale;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


