package entities;
// Generated Jun 7, 2016 9:33:33 PM by Hibernate Tools 4.3.1

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Userkey generated by hbm2java
 */
public class Userkey {


     private int userId;
     private Ranked ranked;
     private String userName;
     private String userPassword;
     private String userImages;
     private String userPhonenum;
     private String userGender;
     private String userAddress;
     private Date userDateofbirth;
     private int money;
     private Set allorders = new HashSet(0);

    public Userkey() {
    }

	
    public Userkey(int userId, Ranked ranked, String userName, String userPassword, int money) {
        this.userId = userId;
        this.ranked = ranked;
        this.userName = userName;
        this.userPassword = userPassword;
        this.money = money;
    }
    public Userkey(int userId, Ranked ranked, String userName, String userPassword, String userImages, String userPhonenum, String userGender, String userAddress, Date userDateofbirth, int money, Set allorders) {
       this.userId = userId;
       this.ranked = ranked;
       this.userName = userName;
       this.userPassword = userPassword;
       this.userImages = userImages;
       this.userPhonenum = userPhonenum;
       this.userGender = userGender;
       this.userAddress = userAddress;
       this.userDateofbirth = userDateofbirth;
       this.money = money;
       this.allorders = allorders;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Ranked getRanked() {
        return this.ranked;
    }
    
    public void setRanked(Ranked ranked) {
        this.ranked = ranked;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserImages() {
        return this.userImages;
    }
    
    public void setUserImages(String userImages) {
        this.userImages = userImages;
    }
    public String getUserPhonenum() {
        return this.userPhonenum;
    }
    
    public void setUserPhonenum(String userPhonenum) {
        this.userPhonenum = userPhonenum;
    }
    public String getUserGender() {
        return this.userGender;
    }
    
    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public Date getUserDateofbirth() {
        return this.userDateofbirth;
    }
    
    public void setUserDateofbirth(Date userDateofbirth) {
        this.userDateofbirth = userDateofbirth;
    }
    public int getMoney() {
        return this.money;
    }
    
    public void setMoney(int money) {
        this.money = money;
    }
    public Set getAllorders() {
        return this.allorders;
    }
    
    public void setAllorders(Set allorders) {
        this.allorders = allorders;
    }




}


